//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLoginHistory
{
    public partial class MobileOtpLogin
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlMobile;
        protected global::System.Web.UI.WebControls.Label lblMobileNumber;
        protected global::System.Web.UI.WebControls.TextBox txtMobileNumber;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMobileNumber;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revMobileNumber;
        protected global::System.Web.UI.WebControls.Button btnSendOtp;
        protected global::System.Web.UI.WebControls.Panel pnlOtp;
        protected global::System.Web.UI.WebControls.Label lblOtpDestination;
        protected global::System.Web.UI.WebControls.Label lblOtp;
        protected global::System.Web.UI.WebControls.TextBox txtOtp;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOtp;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revOtp;
        protected global::System.Web.UI.WebControls.Button btnVerifyOtp;
        protected global::System.Web.UI.WebControls.Button btnResendOtp;
    }
}
